version: "3"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$PASSWORD
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=$EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PASSWORD
    ports:
      - 1337:80
    links:
      - "database:db"
